# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-bcellmagic-2.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.6.11
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  - muscle=3.8.1551
  - vsearch=2.11.1
  - bioconda::fastqc=0.11.8
  - bioconda::multiqc=1.9
  - matplotlib=3.0.3
  - cd-hit=4.8.1
  - blast=2.7.1
  - igblast=1.10.0
  - phylip=3.697
  - tbl2asn=25.6
  - airr=1.2.1
  - presto=0.5.10
  - changeo=0.4.5
  - bioconda::biopython=1.70
  - conda-forge::unzip=6.0
  - conda-forge::zip=3.0
  - conda-forge::ghostscript=9.22
  - conda-forge::pandas=0.24.2
  - conda-forge::seaborn=0.9.0
  - conda-forge::cairo=1.16.0
  - conda-forge::mscorefonts=0.0.1
  - bioconda::phylip=3.697
  - conda-forge::r-base=3.5.1
  - conda-forge::r-alakazam=0.2.11
  - bioconda::r-shazam=0.1.11
  - bioconda::r-tigger=0.3.1
  - conda-forge::r-dplyr=0.8.3
  - conda-forge::r-data.table=1.12.2
  - conda-forge::r-igraph=1.2.4.1
  - conda-forge::r-gplots=3.0.1.1
  - conda-forge::r-circlize=0.4.6
  - conda-forge::r-upsetr=1.4.0
  - conda-forge::r-gtools=3.8.1
  - conda-forge::r-ggplot2=3.2.0
  - conda-forge::r-svglite=1.2.2
  - conda-forge::r-extrafont=0.17
  - conda-forge::r-optparse=1.6.2
  - r-airr=1.2.0