---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - "bioconda::amulety=2.1.1"
  - "conda-forge::wget"
  - "conda-forge::curl"
